### ISSUE TITLE
Are requests with proxy avaliable?

### ISSUE THREAD

**Issue by alikud** [gosom/scrapemate#3]
Hi, can i set proxy to request, when some parse job will be started? I want to use HTTP or SOCKS5 proxy to do some job, because some services have rate limits and etc. If no, can i do merge request ?

**Comment by gosom** [comment]
hi @alikud , 

if you are using the low level api and not using javascript rendering then you can utilize 
the https://pkg.go.dev/github.com/gosom/scrapemate?utm_source=godoc#WithHTTPFetcher to initialize your own http fetcher implementation.

see the  fetcher implementation https://github.com/gosom/scrapemate/blob/main/adapters/fetchers/nethttp/nethttp.go#L20 

since it accepts an HTTP client you can add one initialized with a proxy.

for the high level API without JS there is not such option but it would be nice. 


For the JS rendering this also looks possible to be added since Playwright supports that. However, this is not implemented yet. 

see this code: https://github.com/gosom/scrapemate/blob/main/adapters/fetchers/jshttp/jshttp.go#L125

the proxy settings should go there


if you already have an implementation please make a merge request. 
Otherwise, I will try to add these because it is very useful, though I cannot promise I will find the time to do it withing the next weeks. 

thank you

**Comment by gosom** [comment]
@alikud It's almost a year but proxy support is implemented in v0.7.0
